executor: slurm
jobs: 10
use-conda: true
latency-wait: 60
rerun-incomplete: true
printshellcmds: true
default-resources:
  slurm_account: "u2015037"
  slurm_partition: "main"
  runtime: "60"
  mem_mb: 8000