executor: slurm
jobs: 10
use-conda: true
latency-wait: 60
rerun-incomplete: true
printshellcmds: true
default-resources:
  # slurm_account and slurm_partition are set per-rule from the species config block
  runtime: "60"
  mem_mb: 8000